# Generated by Django 4.1.2 on 2023-05-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
