# Generated by Django 4.1.2 on 2022-10-28 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("points", models.FloatField(default=0)),
                (
                    "profile_pic",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        default=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[50, 50],
                        upload_to="authors",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Manado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kata", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "manado",
            },
        ),
        migrations.CreateModel(
            name="Penilaian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("bobot", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "penilaian",
            },
        ),
        migrations.CreateModel(
            name="Verifikator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "profile_pic",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        default=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[50, 50],
                        upload_to="authors",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
                ("poin", models.FloatField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("best", models.BooleanField(default=False)),
                (
                    "penilai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.verifikator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.author",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "translasi",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=400)),
                ("portal", models.CharField(default="Unknown", max_length=400)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("url", models.URLField(max_length=400)),
                ("tipe", models.CharField(default="Artikel", max_length=400)),
                ("konten", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("kategori", models.ManyToManyField(to="main.category")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                ("translasi", models.ManyToManyField(blank=True, to="main.translasi")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instrumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", tinymce.models.HTMLField()),
                ("nilai", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("penilaian", models.ManyToManyField(to="main.penilaian")),
            ],
            options={
                "verbose_name_plural": "instrumen",
            },
        ),
    ]
