# Generated by Django 4.1.2 on 2022-11-01 06:49

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_post_tags_administrator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="profile_pic",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=200,
                scale=None,
                size=[100, 100],
                upload_to="administrator",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="profile_pic",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=200,
                scale=None,
                size=[100, 100],
                upload_to="authors",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.administrator"
            ),
        ),
        migrations.AlterField(
            model_name="verifikator",
            name="profile_pic",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=200,
                scale=None,
                size=[100, 100],
                upload_to="verifikator",
            ),
        ),
    ]
