# Generated by Django 4.1.2 on 2022-11-01 10:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_administrator_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_pic",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=200,
                scale=None,
                size=[60, 60],
                upload_to="authors",
            ),
        ),
    ]
