# Generated by Django 4.1.2 on 2022-11-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_author_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perbandingan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kalimat_ind", models.TextField()),
                ("kalimat_mdo", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("post", models.ManyToManyField(to="main.post")),
            ],
            options={
                "verbose_name_plural": "perbandingan",
            },
        ),
    ]
