# Generated by Django 4.1.2 on 2022-11-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_perbandingan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perbandingan",
            name="post",
        ),
    ]
