# Generated by Django 4.1.2 on 2022-11-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_kandidat_pollresult_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
