# Generated by Django 4.1.2 on 2022-11-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_post_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.administrator"
            ),
        ),
    ]
