# Generated by Django 4.1.2 on 2022-11-13 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_poll_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kandidat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.author"
            ),
        ),
    ]
