# Generated by Django 4.1.2 on 2022-11-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_poll_result_kandidat_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="poll_ke",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
