# Generated by Django 4.1.2 on 2022-11-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_poll_poll_ke"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="poll_ke",
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
