# Generated by Django 4.1.2 on 2023-05-16 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0015_alter_poll_poll_ke"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifikator",
            name="address",
            field=models.CharField(default="Sulawesi Utara", max_length=400),
        ),
        migrations.AddField(
            model_name="verifikator",
            name="contact",
            field=models.CharField(default="62123412341234", max_length=400),
        ),
        migrations.AddField(
            model_name="verifikator",
            name="field",
            field=models.CharField(default="Linguistik", max_length=400),
        ),
        migrations.AddField(
            model_name="verifikator",
            name="job_role",
            field=models.CharField(default="Penerjemah", max_length=400),
        ),
        migrations.AddField(
            model_name="verifikator",
            name="tipe",
            field=models.CharField(default="Individu", max_length=400),
        ),
        migrations.CreateModel(
            name="BeVerificator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lengkap", models.CharField(max_length=400)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("email", models.CharField(max_length=400)),
                ("tipe", models.CharField(max_length=400)),
                ("field", models.CharField(max_length=400)),
                ("job_role", models.CharField(default="Null", max_length=400)),
                ("contact", models.CharField(max_length=400)),
                ("address", models.CharField(max_length=400)),
                ("proof", models.FileField(upload_to=main.models.user_directory_path)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "berkas",
            },
        ),
        migrations.CreateModel(
            name="ArticleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(blank=True, max_length=250, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url_berita", models.CharField(max_length=400)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
