# Generated by Django 4.1.2 on 2023-05-16 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_verifikator_address_verifikator_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="kategori",
        ),
        migrations.AddField(
            model_name="post",
            name="kategori",
            field=models.ForeignKey(
                default="8",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.category",
            ),
        ),
    ]
