# Generated by Django 4.1.2 on 2023-05-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_beverificator_options_alter_beverificator_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beverificator",
            options={"verbose_name_plural": "BeVerificator"},
        ),
        migrations.AddField(
            model_name="beverificator",
            name="status",
            field=models.CharField(default="Diproses", max_length=400),
        ),
    ]
