# Generated by Django 4.1.2 on 2023-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_verifikator_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dinilai",
            field=models.BooleanField(default=False),
        ),
    ]
