# Generated by Django 4.1.2 on 2023-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_translationnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="anonym",
            field=models.BooleanField(default=False),
        ),
    ]
